application: techevents
version: cleanup
runtime: python
api_version: 1

handlers:


- url: /static/([^/]*)/(.*)
  static_files: static/\2
  upload: static/(.*)
  expiration: "24d"
  
- url: /tasks.*
  script: main.py
  login: admin

- url: .*
  script: main.py
  
builtins:
- datastore_admin: on